function sortearItem(array) {
    const indiceAleatorio = Math.floor(Math.random() * array.length);
    return array[indiceAleatorio];
}

const frases = [
    "Grandes oportunidades estão a caminho.",
    "A felicidade começa com um sorriso.",
    "Confie em seu coração hoje.",
    "Um novo amigo trará alegria em breve.",
    "Seu esforço será recompensado.",
    "A paciência é a chave do sucesso.",
    "Você está prestes a descobrir um talento oculto.",
    "Uma surpresa agradável aguarda você.",
    "Continue acreditando em seus sonhos.",
    "Sua sorte está mudando para melhor.",
    "Um momento de coragem mudará seu destino.",
    "A bondade que você espalha voltará para você.",
    "Prepare-se para uma mudança positiva.",
    "O amor está mais perto do que você imagina.",
    "Novas aventuras estão no seu caminho.",
    "Sua criatividade será valorizada.",
    "A sorte sorri para você hoje.",
    "Confie em sua intuição.",
    "Um desafio será superado com facilidade.",
    "A paz interior é seu maior tesouro.",
    "Seu sorriso é contagiante.",
    "A honestidade trará recompensas inesperadas.",
    "Você está mais forte do que pensa.",
    "Um conselho sábio trará clareza.",
    "Você é capaz de grandes feitos.",
    "O sucesso está ao seu alcance.",
    "Boas notícias chegarão em breve.",
    "A amizade verdadeira é um presente.",
    "Mantenha o foco, grandes coisas vêm aí.",
    "A gratidão abrirá portas.",
    "Você fará uma escolha importante em breve.",
    "Sua energia positiva atrai coisas boas.",
    "Um sonho antigo está prestes a se realizar.",
    "A sorte está ao seu lado.",
    "O equilíbrio é fundamental.",
    "A perseverança é seu maior aliado.",
    "Um gesto simples pode mudar tudo.",
    "Você inspirará alguém hoje.",
    "A felicidade está nas pequenas coisas.",
    "Sua curiosidade levará a descobertas.",
    "Um momento de reflexão trará respostas.",
    "Acredite no poder da mudança.",
    "Um encontro inesperado trará alegria.",
    "O tempo cura todas as feridas.",
    "Sua bondade é uma luz no mundo.",
    "A coragem fará você crescer.",
    "O aprendizado nunca termina.",
    "Seja paciente com você mesmo.",
    "Novas ideias surgirão quando você menos esperar.",
    "Você é uma inspiração para os outros.",
    "Sua determinação abrirá caminhos.",
    "Um segredo será revelado em breve.",
    "A humildade traz grandes recompensas.",
    "Você está no caminho certo.",
    "A gentileza é uma linguagem universal.",
    "Confie no processo da vida.",
    "O amor-próprio é o início de tudo.",
    "Sua intuição é sua melhor guia.",
    "Um passo de cada vez leva longe.",
    "O sucesso vem para quem não desiste.",
    "Você fará a diferença hoje.",
    "Sua mente aberta atrai oportunidades.",
    "A felicidade é uma escolha diária.",
    "Você tem o poder de mudar sua história.",
    "A esperança nunca deve morrer.",
    "Acredite no impossível.",
    "Um ato de bondade mudará seu dia.",
    "A amizade verdadeira é eterna.",
    "Você encontrará paz interior em breve.",
    "O melhor ainda está por vir.",
    "Sua coragem inspira outros.",
    "Um sorriso seu ilumina o dia de alguém.",
    "A vida é cheia de surpresas boas.",
    "Um novo hobby trará alegria.",
    "Você está cercado de boas energias.",
    "A confiança atrai sucesso.",
    "Aprenda com o passado, viva o presente.",
    "Seu talento será reconhecido.",
    "A positividade transforma realidades.",
    "Um momento de silêncio trará clareza.",
    "Sua bondade é seu maior presente.",
    "O amor encontra quem acredita.",
    "Seja a mudança que deseja ver.",
    "O esforço de hoje traz o fruto de amanhã.",
    "Você é capaz de realizar sonhos.",
    "Novos caminhos se abrirão para você.",
    "Sua determinação é admirável.",
    "A felicidade está dentro de você.",
    "Valorize as pessoas ao seu redor.",
    "Uma nova fase começa agora.",
    "A paciência é a virtude dos fortes.",
    "Seu coração está cheio de sabedoria.",
    "Cada dia é uma nova chance.",
    "Acredite no poder da gratidão.",
    "A vida recompensa os corajosos.",
    "Um momento de alegria está próximo.",
    "Você é amado mais do que imagina.",
    "A luz no fim do túnel está próxima.",
    "A sorte acompanha os preparados.",
    "Um futuro brilhante espera por você."
];
  
module.exports = {sortearItem, frases };